### ISSUE TITLE
Not redireting to save_credentials.html

### ISSUE THREAD

**Issue by scottrpaterson** [jasbur/RaspiWiFi#49]
After entering credentials, it does not redirect to save_credentials.html.

It does however correctly save the credentials and reboot. Tested on Firefox 62 with newest img version on Pi Zero W.

It looks like this is happening because in app.py on line 27 is the  set_ap_client_mode function which runs a reboot before it gets to line 29 for redirecting to the save_credentials.html page.

Unrelated question, but in /etc/raspiwifi/raspiwifi.conf does Auto-Config mode check for an "active connection" to the internet via ping or to the local router? It's not clear how iwconfig works in your code for checking.

**Comment by jasbur** [comment]
Neither, I wanted to make sure to account for situations where a user might have a router set up intentionally with no internet access for local commutation between devices (pinging an internet resource would fail here). Also, I wanted to account for situations where firewall rules and unique network topography that might limit the success of pinging the Pi's default gateway or immediate router.

So, I'm actually using the `wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf` command to attempt a connection, then the `wpa_cli -i wlan0 status` command to query for the connection status. It outputs something like:

```
bssid=xx:xx:xx:xx:xx:xx
freq=5180
ssid=My SSID
id=0
mode=station
pairwise_cipher=CCMP
group_cipher=CCMP
key_mgmt=WPA2-PSK
wpa_state=COMPLETED
ip_address=192.168.1.3
p2p_device_address=xx:xx:xx:xx:xx:xx
address=xx:xx:xx:xx:xx:xx
uuid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
```

The I just search for `wpa_state=COMPLETED` in the output. If it's there then that means that the full connection process, including the correct key, has been successful.

Also, I think I know what the problem is regarding the `save_credentials.html` no displaying after a successful connection. I'm working on it in the `authentication_check` branch,

**Comment by jasbur** [comment]
Thanks @alexrj for the fix.
