### ISSUE TITLE
Not getting IP address connecting to AP

### ISSUE THREAD

**Issue by ngmacha** [jasbur/RaspiWiFi#62]
I'm running a ZeroBotPro image (https://hackaday.io/project/25092-zerobot-raspberry-pi-zero-fpv-robot, it's a Jessie with MJPG streaming app and a few GPIO to control two motors) on a Raspberry Pi Zero W. I installed RaspiWiFi, after reboot the AP appears OK, but when connecting to it I get the IP in the 169.254.x.x range. Hence no way to browse to the RaspiWiFi Configuration page. Connecting a display/keyboard to the PiZero and trying to open https://10.0.0.1:9191 gives ERR_CONNECTION_REFUSED....

I have no idea how even to troubleshoot this! And is there a way to cleanly uninstall your app, or I have to rewrite a clean image back? You app might be exactly what I need, but I somehow must make it properly work first! Thank you in advance for help.

**Comment by jasbur** [comment]
There isn't a way to cleanly uninstall RaspiWiFi without re-imaging (...yet). 

The current version of RaspiWiFi, `1.8`, is not compatible with Raspbian Jessie and only works properly with Raspbian Stretch. [Version 1.6](https://github.com/jasbur/RaspiWiFi/releases/tag/v1.6) is the last version with Raspbian Jessie support. I had to drop it because of some changes in the way network configuration is handled between the two versions.
