### ISSUE TITLE
RaspiWiFi breaks DNS for Ethernet connection.

### ISSUE THREAD

**Issue by m-kru** [jasbur/RaspiWiFi#65]
If I install RaspiWiFi then DNS support is broken if I connect my Raspberry Pi via Ethernet to the router.
After rebooting I do not configure RaspiWiFi but connect raspberry to the router. The content of `/etc/resolv.conf` is `nameserver 127.0.0.1`. This forces me to use IP addresses (ping 8.8.8.8 works) instead of names.
Do you know what needs to be changed so that Raspberry could work with DNS via Ethernet even if RaspiWifi is installed?

**Comment by jasbur** [comment]
I don't know offhand, but I'm sure there's got to be some way to work around the issue. The DNS is redirected to allow access to the configuration page using a domain style mainstyle name instead of just the IP address (raspiwifisetup.com).

I'll take a crack at it next time I get a chance to look at the code. It might be a little while since I've got a few other projects for clients going on at the moment. If you come up with a solution feel free to send a pull request.

**Comment by jasbur** [comment]
You could try changing that line to `nameserver 1.1.1.1` or any other DNS server. You would only be able to connect to the RaspiWiFi Configuration Page by using its IP address `10.0.0.1`, but it should probably get all other DNS queries working while in Configuration Mode.

**Comment by ashah7** [comment]
in the /etc/dhcpcd.conf file provided by raspiwifi add the below line
`static domain_name_servers=8.8.8.8 8.8.4.4`
or whatever dns server you want to use
