### ISSUE TITLE
isc-dhcp-server.apclient not in /usr/lib/raspiwifi/reset_device/static_files

### ISSUE THREAD

**Issue by PeterFucci** [jasbur/RaspiWiFi#68]
line 85 of app.py refers to isc-dhcp-server.apclient. This is not located in static files.

**Comment by jasbur** [comment]
It looks like it is a deprecated line that was used in previous versions. It can just be removed since we no longer use isc-dhcp-server at all and instead use dnsmasq for all DHCP functions.

If you have the time in the will feel free to remove it and send a pull request, otherwise I'll make sure to remove it the next time I get a chance to work on the code. Thanks for the heads up.

**Comment by PeterFucci** [comment]
I’ve a MS C++, C# guy. I started python Nov 10th of 2018! I’m not sure I qualify to make the changes 😊

Thanks for making an awesome product!

-p

****************
Peter J. Fucci
Cell:       401.369.1311
Work:401.257.7822
****************

**Comment by jasbur** [comment]
I just took care of this with the most recent commit to the `master` branch. Thanks for the heads up.

**Comment by PeterFucci** [comment]
Thanks!
